### ISSUE TITLE
uncatchable spec crashing the server if used in spawners

### ISSUE THREAD

**Issue by Giovanni291** [EnvyWare/EnvySpecs#1]
Hey, as explained in the title, if you try to use the uncatchable spec in the spawners, the server will just crash, i'll provide the crash-report below. No idea on if you can do anything about it, but would be perfect if you could. If not used inside the spawner it works perfectly

https://pastebin.com/2EPX0jzz

**Comment by danorris709** [comment]
Fixed in the latest version
